# Sales Records Analysis
### Author: Your Name
### Exercise 2.E Using Functions for Analyzing Data

This notebook looks at a small sales dataset using Python functions.
The data includes product names, sales regions, and sale amounts.


In [1]:
sales_data = [
    ('Laptop', 'East', 1200.00),
    ('Phone', 'West', 850.00),
    ('Tablet', 'East', 400.00),
    ('Monitor', 'South', 650.00),
    ('Keyboard', 'West', 75.00),
    ('Laptop', 'South', 1150.00),
    ('Phone', 'East', 900.00),
    ('Tablet', 'West', 425.00),
    ('Monitor', 'East', 680.00),
    ('Keyboard', 'South', 80.00),
    ('Laptop', 'West', 1300.00),
    ('Phone', 'West', 820.00)
]

print(sales_data)

[('Laptop', 'East', 1200.0), ('Phone', 'West', 850.0), ('Tablet', 'East', 400.0), ('Monitor', 'South', 650.0), ('Keyboard', 'West', 75.0), ('Laptop', 'South', 1150.0), ('Phone', 'East', 900.0), ('Tablet', 'West', 425.0), ('Monitor', 'East', 680.0), ('Keyboard', 'South', 80.0), ('Laptop', 'West', 1300.0), ('Phone', 'West', 820.0)]


## Lab 1. Total sales by region

In [3]:
def region_total(data, region):

    total = 0

    for product, sales_region, amount in data:

        if sales_region == region:
            total += amount
            return total




In [4]:
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

1200.0
850.0
650.0


In [5]:
## Lab 2. Count of sales by region

In [6]:
def region_count(data, region):

    count = 0

    for product, sales_region, amount in data:

        if sales_region == region:
            count += 1

    return count

In [7]:
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [8]:
def region_average(data, region):

    total = region_total(data, region)
    count = region_count(data, region)

    if count == 0:
        return 0

    return total / count

In [9]:
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))

300.0
170.0
216.66666666666666
0


## Lab 4. Filter by sale amount

In [10]:
def sales_above(data, threshold):

    results = []

    for record in data:

        if record[2] > threshold:
            results.append(record)

    return results

In [11]:
high_sales = sales_above(sales_data, 500)

for record in high_sales:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


## Lab 5. Top and bottom sale

In [15]:
def top_sale(data):
    return max(data, key=lambda s: s[2])


def bottom_sale(data):
    return min(data, key=lambda s: s[2])

In [16]:
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The highest sale was a Laptop in  West region for $1300.00.

The lowest sale was a Keyboard in West region for $75.00.

## Lab 6. Apply a discount

In [28]:
def apply_discount(data, discount_pct):

    updated_sales = []

    for product, region, amount in data:

        new_amount = amount - (amount * discount_pct)

        updated_sales.append((product, region, new_amount))

    return updated_sales

In [29]:
discounted_sales = apply_discount(sales_data, 0.15)

print("Original:")
for sale in sales_data[:3]:
    print(sale)

print()

print("Discounted:")
for sale in discounted_sales[:3]:
    print(sale)

Original:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

Discounted:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [30]:
def unique_regions(data):

    all_regions = []

    for product, region, amount in data:

        if region not in all_regions:
            all_regions.append(region)

    return sorted(all_regions)

In [31]:
print(unique_regions(sales_data))

['East', 'South', 'West']


This function can help organize and analyze sales data by region.
It could also be useful for creating reports, charts, or checking which regions are included in the dataset.

## Lab 8. Region summary

In [32]:
def region_summary(data, region):

    region_data = []

    for sale in data:

        if sale[1] == region:
            region_data(sale)

    top = top_sale(region_data)

    print(region, "Region")
    print("Number of sales:", region_count(data, region))
    print("Total sales: $", format(region_total(data, region), ".2f"))
    print("Average sale: $", format(region_average(data, region), ".2f"))
    print("Top sale:", top[0], "- $", format(top[2], ".2f"))

In [ ]:
region_summary(sales_data, 'East')

## Lab 9. Full summary

In [ ]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)
    print()

In these labs, I learned how to use functions to analyze a small sales dataset. I practiced finding totals, counts, averages, top sales, discounts, and unique regions. I also learned how smaller functions can work together to make a bigger summary report.